# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vegard Stikbakke
email: vegard.stikbakke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about programming and statistics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vegardstikbakke.com" # the base hostname & protocol for your site

# SEO settings
twitter:
  username: vegardstikbakke
author: Vegard Stikbakke
social:
  name: Vegard Stikbakke
  links:
    - https://twitter.com/vegardstikbakke
    - https://github.com/vegarsti
    - https://www.linkedin.com/in/vegardstikbakke/

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - venv
  - vendor
sass:
  style: compressed

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
